
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button borrartodo;
	private global::Gtk.Button mayusculas;
	private global::Gtk.Button minusculas;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button negrita;
	private global::Gtk.Button cursiva;
	private global::Gtk.Button cerrar;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.borrartodo = new global::Gtk.Button ();
		this.borrartodo.CanFocus = true;
		this.borrartodo.Name = "borrartodo";
		this.borrartodo.UseUnderline = true;
		this.borrartodo.Label = global::Mono.Unix.Catalog.GetString ("Borrar todo");
		this.hbox1.Add (this.borrartodo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.borrartodo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.mayusculas = new global::Gtk.Button ();
		this.mayusculas.CanFocus = true;
		this.mayusculas.Name = "mayusculas";
		this.mayusculas.UseUnderline = true;
		this.mayusculas.Label = global::Mono.Unix.Catalog.GetString ("Mayusculas");
		this.hbox1.Add (this.mayusculas);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.mayusculas]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.minusculas = new global::Gtk.Button ();
		this.minusculas.CanFocus = true;
		this.minusculas.Name = "minusculas";
		this.minusculas.UseUnderline = true;
		this.minusculas.Label = global::Mono.Unix.Catalog.GetString ("Minusculas");
		this.hbox1.Add (this.minusculas);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.minusculas]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.negrita = new global::Gtk.Button ();
		this.negrita.CanFocus = true;
		this.negrita.Name = "negrita";
		this.negrita.UseUnderline = true;
		this.negrita.Label = global::Mono.Unix.Catalog.GetString ("Negrita");
		this.hbox2.Add (this.negrita);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.negrita]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.cursiva = new global::Gtk.Button ();
		this.cursiva.CanFocus = true;
		this.cursiva.Name = "cursiva";
		this.cursiva.UseUnderline = true;
		this.cursiva.Label = global::Mono.Unix.Catalog.GetString ("Cursiva");
		this.hbox2.Add (this.cursiva);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cursiva]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.cerrar = new global::Gtk.Button ();
		this.cerrar.CanFocus = true;
		this.cerrar.Name = "cerrar";
		this.cerrar.UseUnderline = true;
		this.cerrar.Label = global::Mono.Unix.Catalog.GetString ("Cerrar");
		this.hbox2.Add (this.cerrar);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cerrar]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.hbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.GtkScrolledWindow.Add (this.textview2);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w10.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 560;
		this.DefaultHeight = 387;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.borrartodo.Clicked += new global::System.EventHandler (this.OnBorrartodoClicked);
		this.mayusculas.Clicked += new global::System.EventHandler (this.OnMayusculasClicked);
		this.minusculas.Clicked += new global::System.EventHandler (this.OnMinusculasClicked);
		this.negrita.Clicked += new global::System.EventHandler (this.OnNegritaClicked);
		this.cursiva.Clicked += new global::System.EventHandler (this.OnCursivaClicked);
		this.cerrar.Clicked += new global::System.EventHandler (this.OnCerrarClicked);
	}
}
